version: 0.9.7.{build}
init:
- cmd: >-
    pip install --upgrade six

    pip install tox

    pip install coverage

    pip install codacy-coverage

    pip install codecov
environment:
  CODACY_PROJECT_TOKEN:
    secure: JiPmBi3x+D1RDWbWXFLtigq3OJ3sdrOisDjdw4718q8VOlC/oF6Or8i6DPr9SrGs
  CODECOV_TOKEN:
    secure: sOKFWMIx8082DQo03X10a0ZPC4LKKAD2ww1kqtGONrBK+6ZSIBiRtOod4+z3+2am
  matrix:
  - TOXENV: py27
  - TOXENV: py33
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: flake8
  - TOXENV: readme
cache: .tox
build_script:
- cmd: pip install -e .
test_script:
- cmd: tox
deploy: off
on_success:
- cmd: codecov
