version: 0.9.6.{build}
init:
- cmd: >-
    pip install --upgrade six

    pip install tox

    pip install coverage

    pip install codacy-coverage
environment:
  CODACY_PROJECT_TOKEN:
    secure: JiPmBi3x+D1RDWbWXFLtigq3OJ3sdrOisDjdw4718q8VOlC/oF6Or8i6DPr9SrGs
  matrix:
  - TOXENV: py27
  - TOXENV: py33
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: flake8
  - TOXENV: readme
build_script:
- cmd: pip install -e .
test_script:
- cmd: tox
deploy_script:
- cmd: >-
    echo Test Success

    if exist .coverage coverage combine & coverage xml & exit 0

    python-codacy-coverage -r coverage.xml & exit 0
