version: 0.9.9.{build}
skip_tags: true
init:
- cmd: >-
    pip install --upgrade six

    pip install tox

    pip install coverage

    pip install codecov
environment:
  CODECOV_TOKEN:
    secure: sOKFWMIx8082DQo03X10a0ZPC4LKKAD2ww1kqtGONrBK+6ZSIBiRtOod4+z3+2am
  matrix:
  - TOXENV: py27
  - TOXENV: py33
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: flake8
  - TOXENV: readme
cache: .tox
build_script:
- cmd: pip install -e .
test_script:
- cmd: tox
deploy: off
on_success:
- cmd: codecov -e TOXENV
