---
engines:
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      E401:
        enabled: false
      F401:
        enabled: false
  duplication:
    enabled: true
    checks:
      Similar Code:
        enabled: true
    config:
      languages:
        python:
  radon:
    enabled: true
    config:
      threshold: "B"
ratings:
  paths:
  - "awss/*"
  - "setup.py"
exclude_paths:
  - "test/*"
  - ".tox/*"
  - "build/*"
  - "dist/*"
  - "*.egg-info/*"
  - "zref/*"
