---
engines:
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      E401:
        enabled: false
      F401:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
  radon:
    enabled: true
ratings:
  paths:
  - "awss/*"
  - "setup.py"
exclude_paths:
  - ".tox/*"
  - "build/*"
  - "dist/*"
  - "*.egg-info/*"
