---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
ratings:
  paths:
  - "awss/*"
exclude_paths: []
