---
engines:
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      E401:
        enabled: false
      F401:
        enabled: false
ratings:
  paths:
  - "awss/*"
exclude_paths: []
