branches:
  only:
  - master
  - develop
language: python
cache: pip
notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
  - os: linux
    python: 3.5
    env: CACHE_NAME=JOB2
  - os: linux
    python: 2.7
    env: CACHE_NAME=JOB5
before_install:
- python -V
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- pip install -e .
script:
  - python setup.py --long-description | rst2html.py > /dev/null
  - python setup.py check -m -r -s
  - flake8 awss --max-complexity=6
  - py.test -s test
after_success:
  - echo Test Success
  - codeclimate-test-reporter
