branches:
  only:
  - master
  - develop
language: python
before_install:
- if [[ $BREW_PYTHON == 'python3' ]]; then brew update; brew install $BREW_PYTHON; fi
install:
- pip install --upgrade six
before_script:
- pip install tox
- pip install coverage
- pip install codacy-coverage

# test script
script:  tox
notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.5
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=readme
  - os: osx
    language: generic
    env:
    - TOXENV=py27
    - BREW_PYTHON='python'
  - os: osx
    language: generic
    env:
    - TOXENV=py36
    - BREW_PYTHON='python3'

after_success:
  - echo Test Success
  - coverage combine
  - coverage xml
  - python-codacy-coverage -r coverage.xml
