branches:
  only:
  - master
  - develop
language: python
before_install:
- if [[ $TRAVIS_BRANCH == 'develop' ]] && [[ $TRAVIS_OS_NAME = 'osx' ]]; then exit 0; fi
- if [[ $BREW_PYTHON == 'python' ]]; then sudo /usr/bin/easy_install pip; fi
- if [[ $BREW_PYTHON == 'python3' ]]; then brew update; brew install $BREW_PYTHON; alias pip='pip3'; fi
install:
- pip install --upgrade six
- pip install codecov
before_script:
- pip install tox
- pip install coverage
- pip install codacy-coverage

# test script
script:  tox
notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.5
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=bandit
  - python: 2.7
    env: TOXENV=readme
  - os: osx
    language: generic
    env:
    - TOXENV=py27
    - BREW_PYTHON='python'
  - os: osx
    language: generic
    env:
    - TOXENV=py36
    - BREW_PYTHON='python3'

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TOXENV || echo "Codecov did not collect coverage reports"
  - coverage xml
  - python-codacy-coverage -r coverage.xml
