branches:
  only:
  - master
  - develop
language: python
notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
  - os: linux
    python: 3.4
  - os: linux
    python: 2.7
  - os: osx
    language: generic
    env: BREW_PYTHON='python'
  - os: osx
    language: generic
    env: BREW_PYTHON='python3'
before_install:
- if [[ $BREW_PYTHON == 'python3' ]]; then brew update; brew install $BREW_PYTHON;
  python3 -m venv venv; source venv/bin/activate; fi
install:
- pip install --upgrade pip
- pip install --upgrade readme_renderer
- pip install --upgrade flake8
- pip install -e .
script:
- python setup.py check -m -r -s
- flake8 --ignore=E501 awss
after_success:
- echo done
env:
  global:
  - secure: 
deploy:
  provider: pypi
  user: robertpeteuil
  password:
    secure: H8hRA3NPFOkuvPMSJOv69zvSVownLcR8j1uYhKhULxWKLKnzHay1c+v14XJo2WQ1/oUUncjx6gi/UIQx8nYfxElmybVRYqjauabNW/HORtQcEBqWVpLPFWNrY+LJPcxYqijT1ifP73JHkBqz8qBV1tnph849iq3DNsm3PbLpndWWiTsxklUBuom00O6OirHJqhvwfroHwMWozDfzhG10qw5ABTl8xaAbkXeekqTZlLVMZCUbKzBipxBTj0mnAf1V2nwGmpXkckrxJls2yanwEfqaSE2AoZpktmOzsy4qNzX94lEXJ4fDBTZYVgN5hK+aQOemGSfUwhtXZlHJS90INE17tbyYrzec0kY1CRLWmzQyyMKiAo+IgHRL2d47gZwkPfZYBhH84BHaRKx8jX7rH8aCmy73MhzyqOpSjejZTRMJ1KchxtMWMtLomILTUkz5D+6cDp5moCySrj3Iu92VuknaDDZv/yvTjLwqoQYHcte+nAVQbLTGEEkuK0z7uB/LOU1U+PIZgXDkBESTzVWNua5HWVc/5+BBwbjy12Dec6OYqYcxjZWSie/LakMXb6hyCt7BIw9wiXpg85gAYFd78SItTE3aC4MqoUEjwEdrsI52uhq4240JWaYNmcORqJT5KXJeZBNCkzvYF5LAh5azPjNSJgmk3bc74koOTi/PuPc=
  on:
    tags: true
