branches:
  only:
  - master
  - develop
language: python
install:
- pip install --upgrade six
- pip install codecov
before_script:
- pip install tox
- pip install coverage
- pip install codacy-coverage

# test script
script:  tox
notifications:
  email:
    on_success: never
    on_failure: never

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.5
    env: TOXENV=flake8
  - python: 2.7
    env: TOXENV=bandit
  - python: 2.7
    env: TOXENV=readme

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TOXENV || echo "Codecov did not collect coverage reports"
  - coverage xml
  - python-codacy-coverage -r coverage.xml
